# -*- coding: utf-8 -*-
"""var.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlzW3v0XpCQ8YniXaQyIOuUbmgU7eJI6

### Load the packages
"""

from google.colab import drive
drive.mount('/content/drive')

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = '/content/drive/MyDrive/проекты/artyom/JulyRatings/'

"""### Load the data and precompute the daily returns"""

df_ru000A103331 = pd.read_excel(f'{path}RU000A103331_2Y.xlsx')

df_ru000A103331.head(2)

df_ru000A103331['ΔLAST за день, %'] = df_ru000A103331['СЧА'].sort_index(ascending=False).pct_change().dropna()

df_ru000A103331.head(2)

returns = df_ru000A103331['ΔLAST за день, %'].iloc[:-1]

"""### Historical VaR"""

confidence_level = 0.95
var = np.percentile(returns, (1 - confidence_level) * 100)
print(f"Value at Risk (VaR) at {confidence_level*100}% confidence level is {var:.2%}")

plt.figure(figsize=(10, 6))
plt.hist(returns, bins=50, alpha=0.75, color='blue', edgecolor='black')
plt.axvline(x=var, color='red', linestyle='--', label=f'VaR ({confidence_level*100}%)')
plt.title('Distribution of Returns with VaR')
plt.xlabel('Returns')
plt.ylabel('Frequency')
plt.legend()
plt.show()

#VaR annualization
period = 252 # n of days
var_1y = var * math.sqrt(period)
print(f"1Y Value at Risk (VaR) at {confidence_level*100}% confidence level is {var_1y:.2%}")

"""### CVaR aka Expected Shortfall"""

var_threshold = np.percentile(returns, (1 - confidence_level) * 100)
tail_losses = returns[returns < var_threshold]

cvar = tail_losses.mean()
print(f"Conditional Value at Risk (CVaR) at {confidence_level*100}% confidence level is {cvar:.2%}")

plt.figure(figsize=(10, 6))
plt.hist(returns, bins=50, alpha=0.75, color='blue', edgecolor='black')
# plt.axvline(x=var, color='red', linestyle='--', label=f'VaR ({confidence_level*100}%)')
plt.axvline(x=cvar, color='green', linestyle='--', label=f'CVaR ({confidence_level*100}%)')
plt.title('Distribution of Returns with CVaR')
plt.xlabel('Returns')
plt.ylabel('Frequency')
plt.legend()
plt.show()

"""### Normality Tests

#### Q-Q plot
"""

import statsmodels.api as sm

#create Q-Q plot with 45-degree line added to plot (brought to % from absolute values, as the abs change is too close to 0.0)
fig = sm.qqplot(returns*100, line='45')

plt.show()

"""#### Shapiro-Wilk Test

The null-hypothesis is that the data comes from a normal distribution.
"""

from scipy.stats import shapiro

if shapiro(returns*100)[1] <= 0.05:
  print('The data is not normally distributed')
else:
  print('The data is normally distributed')

"""#### Kolmogorov-Smirnov Test

The null-hypothesis is that the data comes from a normal distribution.
"""

from scipy.stats import kstest

if kstest(returns*100, 'norm')[1] <= 0.05:
  print('The data is not normally distributed')
else:
  print('The data is normally distributed')

"""### Sources:
1. [Risk Metrics in Python: VaR and CVaR Guide](https://www.pyquantnews.com/free-python-resources/risk-metrics-in-python-var-and-cvar-guide)
2. [How to Test for Normality in Python (4 Methods)](https://www.statology.org/normality-test-python/)

"""