[theme]
base                     = "light"
backgroundColor          = "#F4FAF7"
secondaryBackgroundColor = "#EBF5EF"
textColor                = "#1A2B23"
primaryColor             = "#0C7A56"
font                     = "sans serif"

